sudo: true
dist: trusty
language: cpp

before_script:
- sudo apt-get install -y build-essential automake libusb-1.0-0-dev libusb-1.0-0 libplist1 libplist-dev libimobiledevice4 libimobiledevice-dev libtool pkg-config

script:
- "./autogen.sh"
- "./configure --prefix=$HOME/out"
- make

after_success:
- make install
- tar -zcvf usbmuxd.tar.gz -C $HOME/out
